#!/bin/sh
# Generate container-local ~/.gitconfig that inherits host settings
# but overrides credential helpers to use the container's gh CLI.
#
# The host's .gitconfig is bind-mounted read-only at ~/.gitconfig-host.
# This script creates ~/.gitconfig with an include directive plus
# container-appropriate credential helper overrides.

GITCONFIG="$HOME/.gitconfig"
GH_BIN="$(command -v gh 2>/dev/null || echo /usr/bin/gh)"

cat > "$GITCONFIG" <<EOF
# Auto-generated by devcontainer setup — do not edit.
# Host settings (user.name, user.email, aliases, etc.) are inherited below.
[include]
    path = ~/.gitconfig-host

# Override credential helpers for the container environment.
# The empty-string entry resets any helpers inherited from the host config.
[credential "https://github.com"]
    helper =
    helper = !${GH_BIN} auth git-credential

[credential "https://gist.github.com"]
    helper =
    helper = !${GH_BIN} auth git-credential
EOF

echo "setup-gitconfig: wrote $GITCONFIG (gh: $GH_BIN)"
